name: Build and deploy JAR app to Azure Web App - Nexus-Sutrava

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        working-directory: backend
        run: mvn clean install

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ${{ github.workspace }}/backend/target/*.jar

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_87FCB3945A5C4F2298E7F599C2A47213 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BE464CFDC1D84DC1984EE65C87A91160 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_05CB964A82AD4F8396C4AC2BE9B3D2F3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: Nexus-Sutrava
          slot-name: Production
          package: '*.jar'
